const steps = [
    {
        target: "#home",
        content: "Welcome to our app! Spend a moment to discover its features. Click here to reach the homepage.",
    },
    {
        target: "#map",
        content: "You are currently on the map page, the application's core page.",
    },
    {
        target: "#highlights",
        content: "Learn more about the finest attractions of Manhattan, New York by clicking here.",
    },
    {
        target: ".closemenu",
        content: "Expand the sidebar to access additional options.",
    },
    {
        target: "#zone-busyness",
        content: "Visualize the predicted busyness of Manhattan zones at any time & date of your choice.",
    },
    {
        target: "#besttime",
        content: "Explore Manhattan using this feature! Find out your favorite venue's busyness, or filter venues based on attraction type, proximity, busyness, and more!",
    },
    {
        target: "#itinerary",
        content: "Generate an itinerary for Manhattan's top 20 attractions or based on your favorite saved venues!",
    },
    {
        target: "#weather",
        content: "Click here to generate a weather forecast for the next 5 days.",
    },
    {
        target: "#user-marker",
        content: "Generate this marker by clicking on the map. This marker is crucial for utilizing the nearby search in the Search Venue feature, as well as displaying routes for any selected venues and for itineraries.",
        placement: "right",
    },
    {
        target: "#top20-marker",
        content: "These markers are generated by default to represent the top 20 attractions of Manhattan. These markers can be toggled on & off.",
        placement: "right",
    },
    {
        target: "#besttime-marker",
        content: "These markers are populated for any venue suggested by the Search Venue feature. ",
        placement: "right",
    },
    {
        target: "#savedplace-marker",
        content: "Saving a venue will generate this marker on the map. To save (or unsave) a venue, first click on any marker on the map, then click on the save/unsave button inside the drawer. These markers can be toggled on & off.",
        placement: "right",
    },
    {
        target: "#zone-toggle",
        content: "Click to toggle the zones on & off.",
        placement: "right",
    },
    {
        target: "#legend-toggle",
        content: "Click to toggle the legends on & off.",
        placement: "right",
    },
    {
        target: "#top20-toggle",
        content: "Click to toggle the top 20 attractions' markers on & off.",
        placement: "right",
    },
    {
        target: "#savedplace-toggle",
        content: "Click to toggle the saved places' markers on & off.",
        placement: "right",
    },
  ]

  export default steps;