# Generated by Django 4.2.2 on 2023-07-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_address', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('opening_hours', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Venue',
            },
        ),
        migrations.CreateModel(
            name='VenueData',
            fields=[
                ('venue_id', models.ForeignKey(db_column='venue_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.venue')),
                ('busyness_monday', models.CharField(max_length=100)),
                ('busyness_tuesday', models.CharField(max_length=100)),
                ('busyness_wednesday', models.CharField(max_length=100)),
                ('busyness_thursday', models.CharField(max_length=100)),
                ('busyness_friday', models.CharField(max_length=100)),
                ('busyness_saturday', models.CharField(max_length=100)),
                ('busyness_sunday', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('scrape_date', models.BigIntegerField()),
            ],
            options={
                'db_table': 'VenueData',
            },
        ),
    ]
