# Generated by Django 4.2.2 on 2023-07-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_delete_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
