# Generated by Django 4.1.10 on 2023-07-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_venuedata_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(max_length=20, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="SavedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place1", models.CharField(max_length=100)),
                ("place2", models.CharField(max_length=100)),
                ("place3", models.CharField(max_length=100)),
                ("place4", models.CharField(max_length=100)),
                ("place5", models.CharField(max_length=100)),
                ("place6", models.CharField(max_length=100)),
                ("place7", models.CharField(max_length=100)),
                ("place8", models.CharField(max_length=100)),
                ("place9", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={
                "db_table": "SavedPlace",
            },
        ),
    ]
