# Generated by Django 4.2.2 on 2023-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_venuedata_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_friday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_monday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_saturday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_sunday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_thursday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_tuesday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='busyness_wednesday',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
