# Generated by Django 4.2.2 on 2023-07-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_venuedata_busyness_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='opening_hours',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
