# Generated by Django 4.2.2 on 2023-08-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_savedplace_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavedPlace",
        ),
    ]
