# Generated by Django 4.2.2 on 2023-08-07 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0008_delete_savedplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_place", models.CharField(max_length=100)),
                (
                    "username",
                    models.ForeignKey(
                        db_column="username",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "venue_id",
                    models.ForeignKey(
                        db_column="venue_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.venue",
                    ),
                ),
            ],
            options={
                "db_table": "SavedPlace",
                "unique_together": {("username", "saved_place")},
            },
        ),
    ]
